
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goingOK
    username: root
    password: kvcc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart: 
      max-file-size: 5MB
      max-request-size: 5MB
        
  
    
